baseURL = 'https://cegepmv.github.io/420-410'
languageCode = 'fr-ca'
title = 'Introduction aux plateformes IdO'
theme = 'relearn'
defaultContentLanguage = "fr"
enableEmoji = true

[params]  
  additionalCSS = ["css/custom.css"]
  disableInlineCopyToClipBoard = true

  [params.imageEffects]
    border = false
    lazy = true
    lightbox = false
    shadow = false

  [[params.themeVariant]]
    auto = []
    identifier = 'relearn-auto'
    name = 'Relearn Light/Dark'

  [[params.themeVariant]]
    identifier = 'zen-light'

  [[params.themeVariant]]
    identifier = 'zen-dark'

  [[params.themeVariant]]
    identifier = 'neon'

  [[params.themeVariant]]
    identifier = 'learn'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = false
    style = "dracula"  # or any theme you like

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
  [languages.fr]
    languageCode = 'fr'
    languageName = 'Fran√ßais'
    title = 'Introduction aux plateformes IdO'
    weight = 1
